<?php
/**
 * @file
 * Code for the FFVCOOP Commerce Init feature.
 */

include_once 'ffvcoop_commerce_init.features.inc';

/*
 * Implements hook_commerce_checkout_complete
 *
 * Set the last order date on user and customer entities
 * If an annual fee is included, set the annual fee date also
 */

function ffvcoop_commerce_init_commerce_checkout_complete($order){
  $existingUser = user_load($order->uid);
    // todo check for annal fee and if so add date below
    $annual_fee=FALSE;
  $existingUser->field_order_count['und'][0]['value'] = intval($existingUser->field_order_count['und'][0]['value']) +1;
  $existingUser->field_last_order_date = array(
            'und' => array(
                0 => array(
                    'value' => date('Y-m-d', time()),
                    'timezone' => 'America/New_York',
                    'timezone_db' => 'America/New_York',
                    'date_type' => "datetime",
                ),
            ),
        );
    if($annual_fee) {
        $existingUser->field_annual_fee = array(
            'und' => array(
                0 => array(
                    'value' => date('Y-m-d', time()),
                    'timezone' => 'America/New_York',
                    'timezone_db' => 'America/New_York',
                    'date_type' => "datetime",
                ),
            ),
        );
    }
    user_save((object) array('uid' => $existingUser->uid), (array) $existingUser);

    // update the customer node type also
    $nodeQuery = new EntityFieldQuery();
    $nodeQuery->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'customer')
        ->fieldCondition('field_customer_email','email', $existingUser->mail, '=')
        ->range(0, 1); //limit to one result
    $customer = $nodeQuery->execute();
    if (isset($customer['node'])) {
        $entity_id = array_keys($customer['node']);
        if ($entity_id) {
            $node = node_load($entity_id[0]);
            if($annual_fee) {
                $node->field_annual_fee = $existingUser->field_annual_fee;
            }
            $node->field_last_order_date = $existingUser->field_last_order_date;
            $node->field_user_reference['und'][0]['target_id'] = $existingUser->uid;
            // save node
            node_save($node);
        }
    }
}

/*
 * Implements hook_user_presave
 *
 * When a user is created or updated, check if a customer value already exists,
 * if so, copy values over to the customer and set the relationship
 */
function ffvcoop_commerce_init_user_presave(&$edit, $account, $category){
    //check if customer node exists with same email
    $nodeQuery = new EntityFieldQuery();
    $nodeQuery->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'customer')
        ->fieldCondition('field_customer_email','email', $account->mail, '=')
        ->range(0, 1); //limit to one result
    $customer = $nodeQuery->execute();
    if (isset($customer['node'])) {
        $entity_id = array_keys($customer['node']);
        if ($entity_id) {
            $node = node_load($entity_id[0]);
            $node->field_customer_email['und'][0]['email'] = $edit['mail'];
            $node->field_annual_fee  = $edit['field_annual_fee'];
            $node->field_last_order_date = $edit['field_last_order_date'];
            $node->title = $edit['field_customer_first_name']['und'][0]['value'];
            $node->field_customer_last_name = $edit['field_customer_last_name'];
            // save node
            node_save($node);
        }
    } else {
      // create a new customer record
        $entity = entity_create('node', array('type' => 'customer'));
        $entity->uid = 1;
        $wrapper = entity_metadata_wrapper('node', $entity);
        $wrapper->title = $edit['field_customer_first_name']['und'][0]['value'];
        $wrapper->field_customer_email = $edit['mail'];
        $wrapper->field_customer_last_name = $edit['field_customer_last_name']['und'][0]['value'];

        // - dont have a UID yet so cant set it here.
        $wrapper->save();


    }
}

/**
 * Implements hook_menu()
 */
function ffvcoop_commerce_init_menu(){
  $items = array();
  $items['manage/weekly-product-report'] = array (
    'title' => 'Weekly Product Report',
    'description' => 'Manage the Pickup Dates calendar',
    'page callback' => 'line_item_report_page',
    'access arguments' => array('access site reports'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function line_item_report_page(){
  return '<h2>Weekly Order Summary</h2>' . drupal_render(drupal_get_form('line_item_date_select_form')) . '<div id="line-item-results"></div>';
}

function line_item_date_select_form($form, &$form_state){
  $form['week_date'] = array(
    '#type' => 'date_popup',
    '#date_format' => 'Y-m-d',
    '#date_year_range' => '-1:+0',
    '#required' => TRUE,
    '#title' => t("Select the Pickup Date"),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#ajax' => array(
      'callback' => 'line_item_date_select_form_submit',
      'wrapper' => 'line-item-results',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );

  return $form;
}

function line_item_date_select_form_submit($form, &$form_state){
  $qty=array();
  $report = '<ul>';
  $query = new EntityFieldQuery();
  $date = $form_state['values']['week_date'];

  $query->entityCondition('entity_type', 'commerce_line_item')
    ->propertyCondition('type','product','=')
    ->addMetaData('account', user_load(1)); // Run the query as user 1.

  $result = $query->execute();

  if (isset($result['commerce_line_item'])) {
    $items_nids = array_keys($result['commerce_line_item']);
    $items = entity_load('commerce_line_item', $items_nids);
    foreach($items as $item){
      $item_wrapper = entity_metadata_wrapper('commerce_line_item', $item->line_item_id);
      if(get_order_pickup_date($item->order_id) == $form_state['values']['week_date']){
        if($name = is_line_item_a_product($item_wrapper)){
          //do something
          $qty[$name] = $qty[$name] + intval($item->quantity);
        }
      }
    }
    foreach($qty as $title=>$value){
      $report.= '<li class="row-summary">' . $title . ' - <span class="total">' . $value . '</span></li>';
    }
  }
  $report .='</ul>';
return $report;
}

function is_line_item_a_product($line_item_wrapper){
  $type = $line_item_wrapper->commerce_product->product_id->value();
  $product_item = commerce_product_load($type);
  $product_type = $product_item->type;
  if($product_type!='product'){
    return FALSE;
  }
  return $product_item->title;
}

function get_order_pickup_date($order_id){
  $order = commerce_order_load($order_id);
  if(in_array($order->status, array('charged', 'cardonfile_charged', 'completed', 'pickedup/delivered'))){
  $date = date('Y-m-d', $order->field_week_date['und'][0]['value']);
   return $date;
  }
  return FALSE;
}